# calc_mean_and_std.yaml
# List out all of the directories containing images used in the training scheme
image_dirs:
  - 'data/PGCView_v2/renamed_images'
device: cuda
out_path: 'metadata/dataset_norm.json'