# Training configs
model_run: dlv3p_enb1

# Computation Device
device: cuda

# Images
images:
  resize: [1024, 1024]

# Metadata for normalization
metadata:
  norm_path: metadata/dataset_norm.json

# Logging
logging_level: DEBUG
tb_exclude_classes: [8, 9, 10, 11]

# Directories
directories:
  train_labeled_dir: data/processed/train/labeled
  train_unlabeled_dir: data/processed/train/unlabeled
  val_dir: data/processed/val
  test_dir: data/processed/test
  output_dir: outputs
  checkpoint_dir: model_checkpoints
  log_dir: logs/run_logs

# Training
training:
  epochs: 40
  sanity_check: True

# Model Architecture
model:
  architecture: DEEPLABV3PLUS
  config:
    encoder_name: efficientnet-b1
    encoder_depth: 5
    encoder_weights: imagenet
    input_channels: 3
    classes: 12

# Optimizer stuff
optimizer:
  name: AdamW
  weight_decay: 0.0001
  filter_bias_and_bn: True
  ema: True
  ema_decay: 0.9
  optimizer_params: 
    lr: 0.003
    momentum: 0.9
    nesterov: True
    gamma: 0.99

# Scheduler stuff
scheduler:
  name: ExponentialLR
  gamma: 0.99

# Criterion / Loss Function
loss:
  name: RECALLLOSS
  class_sample_count_path: 'metadata/class_sample_counts.json'
  reduction: mean
  use_weights: false
  loss_type: FOCALLOSS

# Batch Sizes
batch_size:
  labeled: 6
  unlabeled: 2

# Flexmatch
flexmatch:
  tau: 0.95
  mapping: linear
  warmup: True
